In [1]:
import pandas as pd 
df = pd.read_csv("ДЗ_Pandas.csv")

,ID,Название фильма,Год выпуска,Жанр,Рейтинг,Бюджет (млн $),Сборы (млн $),Режиссер,Основные актеры
0,1,Космический эпос,2022,Фантастика,7.8,120.0,500,NaN,"Анна Петрова, Петр Сидоров"
1,2,Приключения времени,2020,Приключения,8.2,90.0,450,Мария Смирнова,"Сергей Васильев, Ольга Иванова"
2,3,Сердце океана,2021,Драма,8.5,60.0,300,Алексей Попов,"Дмитрий Кузнецов, Ирина Лебедева"
3,4,Секретные агенты,2019,Боевик,7.6,85.0,550,Кирилл Соколов,"Елена Романова, Артем Михайлов"
4,5,Загадка джунглей,2023,Приключения,7.0,NaN,350,Петр Ильин,"Антон Зайцев, Марина Краснова"
5,6,Городские легенды,2018,Триллер,NaN,40.0,200,Ольга Петрова,"Игорь Николаев, Екатерина Волкова"
6,7,Звёздные врата,2023,Научная фантастика,NaN,130.0,650,NaN,"Наталья Орлова, Антон Краснов"
7,8,Возвращение героя,2021,Боевик,7.9,95.0,480,Роман Васильев,"Максим Андреев, Алиса Горшкова"
8,9,Ночные гонки,2019,Драма,7.3,NaN,270,Елена Козлова,"Алексей Петров, Мария Сергеева"
9,10,Тайны прошлого,2022,Мистика,7.1,65.0,310,Дмитрий Иванов,"Светлана Иванова, Денис Смирнов"

In [6]:
#Task 1
df.isnull().sum()
df.dropna(subset = ["Бюджет (млн $)"], inplace = True)
df.fillna({"Режиссер":"Неизвестен"}, inplace = True)
df.fillna({"Рейтинг": df["Рейтинг"].mean()}, inplace = True)
df.dropna(subset = ["Бюджет (млн $)", "Сборы (млн $)"], how = "all", inplace = True)
df

,ID,Название фильма,Год выпуска,Жанр,Рейтинг,Бюджет (млн $),Сборы (млн $),Режиссер,Основные актеры
0,1,Космический эпос,2022,Фантастика,7.80,120.0,500,Неизвестен,"Анна Петрова, Петр Сидоров"
1,2,Приключения времени,2020,Приключения,8.20,90.0,450,Мария Смирнова,"Сергей Васильев, Ольга Иванова"
2,3,Сердце океана,2021,Драма,8.50,60.0,300,Алексей Попов,"Дмитрий Кузнецов, Ирина Лебедева"
3,4,Секретные агенты,2019,Боевик,7.60,85.0,550,Кирилл Соколов,"Елена Романова, Артем Михайлов"
5,6,Городские легенды,2018,Триллер,7.85,40.0,200,Ольга Петрова,"Игорь Николаев, Екатерина Волкова"
6,7,Звёздные врата,2023,Научная фантастика,7.85,130.0,650,Неизвестен,"Наталья Орлова, Антон Краснов"
7,8,Возвращение героя,2021,Боевик,7.90,95.0,480,Роман Васильев,"Максим Андреев, Алиса Горшкова"
9,10,Тайны прошлого,2022,Мистика,7.10,65.0,310,Дмитрий Иванов,"Светлана Иванова, Денис Смирнов"

In [26]:
#Task 2
#Группировка по Жанру
grouped_df = df.groupby("Жанр")
means = grouped_df[["Бюджет (млн $)", "Рейтинг"]].mean()
print(means)

#Группировка по Году Выпуска
group_year = df.groupby("Год выпуска")
total_sales = group_year["Сборы (млн $)"].agg(["sum", 'count'])
print(total_sales)

#Комбинированная Группировка
combined = df.groupby(["Жанр","Год выпуска"])
rating = combined["Рейтинг"].mean()
print(rating)

                    Бюджет (млн $)  Рейтинг
Жанр
Боевик                        90.0     7.75
Драма                         60.0     8.50
Мистика                       65.0     7.10
Научная фантастика           130.0     7.85
Приключения                   90.0     8.20
Триллер                       40.0     7.85
Фантастика                   120.0     7.80
             sum  count
Год выпуска
2018         200      1
2019         550      1
2020         450      1
2021         780      2
2022         810      2
2023         650      1
Жанр                Год выпуска
Боевик              2019           7.60
                    2021           7.90
Драма               2021           8.50
Мистика             2022           7.10
Научная фантастика  2023           7.85
Приключения         2020           8.20
Триллер             2018           7.85
Фантастика          2022           7.80
Name: Рейтинг, dtype: float64

In [16]:
#Task 3 Группировка и Сортировка
grouped_genre = df.groupby("Жанр")
grouped_genre["Рейтинг"].mean().reset_index().sort_values("Рейтинг", ascending = False)

                 Жанр  Рейтинг
1               Драма     8.50
4         Приключения     8.20
3  Научная фантастика     7.85
5             Триллер     7.85
6          Фантастика     7.80
0              Боевик     7.75
2             Мистика     7.10

In [24]:
#Task 3 Анализ частоты
df["Год выпуска"].value_counts().sort_index().reset_index()

   Год выпуска  count
0         2018      1
1         2019      1
2         2020      1
3         2021      2
4         2022      2
5         2023      1

In [29]:
#Task 3 Комбинированный Анализ
new_df = df.groupby(["Режиссер","Жанр"])
new_df["Сборы (млн $)"].sum().reset_index().sort_values("Сборы (млн $)", ascending = False)

         Режиссер                Жанр  Сборы (млн $)
4      Неизвестен  Научная фантастика            650
2  Кирилл Соколов              Боевик            550
5      Неизвестен          Фантастика            500
7  Роман Васильев              Боевик            480
3  Мария Смирнова         Приключения            450
1  Дмитрий Иванов             Мистика            310
0   Алексей Попов               Драма            300
6   Ольга Петрова             Триллер            200